"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_controller_1 = require("../controller/auth.controller");
var router = express_1.default.Router();
router.post("/signup", auth_controller_1.signup);
router.post("/login", auth_controller_1.login);
router.post("/logout", auth_controller_1.logout);
router.post("/refresh", auth_controller_1.refreshToken);
router.post("/email/verify/:token", auth_controller_1.verifyEmailController);
router.post("/password/forgot", auth_controller_1.verifyAuth, auth_controller_1.forgotPassword);
router.patch("/password/reset/:token", auth_controller_1.resetPassword);
router.patch("/password/update", auth_controller_1.verifyAuth, auth_controller_1.updatePassword);
exports.default = router;
